#!/bin/bash

dig() {
	command dig +noall +answer "$1" "$2" | grep "\t$1\t" | sed -E $'s/\t+/ /gp' | cut -d' ' -f5 | head -n 1
}

if [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; then
	echo "Usage: $0 [HOSTNAME/IP]"
	exit
fi

ip="$(echo "$1" | tr A-Z a-z)"

if [[ -z $ip ]] || grep -qE "^(([0-9]{1,3}\.){3}[0-9]{1,3}|([0-9a-f]{1,4}:)+(:?[0-9a-f]{1,4})+)$" <<< "$ip"; then
	:
elif grep -qE "^([a-z0-9_-]+\.)+[a-z0-9_-]+$" <<< "$ip"; then
	ip="$(dig A "$1")"

	if [[ -z $ip ]]; then
		ip="$(dig AAAA "$1")"

		if [[ -z $ip ]]; then
			echo "Domain $1 has no A/AAAA records."
			exit 1
		fi
	fi
else
	echo "Invalid IP address or domain."
	exit 1
fi

curl -sSf "https://ipinfo.io/$ip" && echo
