#!/bin/bash

is_valid_ip() {
	grep -qE "^(([0-9]{1,3}\.){3}[0-9]{1,3}|([0-9a-f]{1,4}:)+(:?[0-9a-f]{1,4})+)$" <<< "$1"
}

dnsquery() {
	dig +noall +answer "$1" "$2" | awk '{ print $5 }' | tail -n 1
}

if [[ $1 == '--help' ]] || [[ $1 == '-h' ]]; then
	echo "Usage: $0 [HOSTNAME/IP]"
	exit
fi

ip="$(echo "$1" | tr A-Z a-z)"

if [[ -z $ip ]] || is_valid_ip "$ip"; then
	:
elif grep -qE "^([a-z0-9_-]+\.)+[a-z0-9-]+$" <<< "$ip"; then
	ip="$(dnsquery A "$ip")"

	if [[ -z $ip ]]; then
		ip="$(dnsquery AAAA "$ip")"

		if [[ -z $ip ]]; then
			echo "Domain $1 has no A/AAAA records."
			exit 1
		fi
	fi
else
	echo "Invalid IP address or domain."
	exit 1
fi

curl -sSf "https://ipinfo.io/$ip" && echo
