#!/usr/bin/env python3


import sys
import random
import argparse
from signal import signal, SIGPIPE, SIG_DFL


def shuf_and_print(f):
    lines = f.readlines()
    random.shuffle(lines)
    for line in lines:
        print(line, end='')


def main():
    signal(SIGPIPE, SIG_DFL)

    parser = argparse.ArgumentParser(
        description='Generate random permutations of lines in a file.'
    )
    parser.add_argument('file', nargs='*', help='input file(s)')
    args = parser.parse_args()

    rv = 0

    try:
        if not args.file:
            try:
                shuf_and_print(sys.stdin)
            except IOError as e:
                sys.stderr.write('%s\n' % e)
                rv = 1
        else:
            try:
                for file in args.file:
                    with open(file, 'r') as f:
                        shuf_and_print(f)
            except IOError as e:
                sys.stderr.write('%s\n' % e)
                rv = 1
    except KeyboardInterrupt:
        pass

    sys.exit(rv)


if __name__ == '__main__':
    main()
