#!/usr/bin/env python3

import sys
import random
from collections import OrderedDict
from signal import signal, SIGPIPE, SIG_DFL

signal(SIGPIPE, SIG_DFL)

def shuf_and_print(f):
    lines = f.readlines()
    random.shuffle(lines)
    for line in lines:
        print(line, end='')

if len(sys.argv) > 1 and sys.argv[1] in ['-h', '--help']:
    print('Generate random permutations of lines in a file.')
    print('Usage: %s file [file ...]' % sys.argv[0])
    sys.exit(0)

args = sys.argv[1:]
rv = 0

try:
    if not args:
        try:
            shuf_and_print(sys.stdin)
        except IOError as e:
            sys.stderr.write('%s\n' % e)
            rv = 1
    else:
        try:
            for arg in args:
                with open(arg, 'r') as f:
                    shuf_and_print(f)
        except IOError as e:
            sys.stderr.write('%s\n' % e)
            rv = 1
except KeyboardInterrupt:
    pass

sys.exit(rv)
